#!r6rs

(import (rnrs)
        (yuni scheme tests racket-r6rs test)
        (yuni scheme tests racket-r6rs base)
        (yuni scheme tests racket-r6rs reader)
        (yuni scheme tests racket-r6rs unicode)
        (yuni scheme tests racket-r6rs bytevectors)
        (yuni scheme tests racket-r6rs lists)
        (yuni scheme tests racket-r6rs sorting)
        (yuni scheme tests racket-r6rs control)
        (yuni scheme tests racket-r6rs records syntactic)
        (yuni scheme tests racket-r6rs records procedural)
        (yuni scheme tests racket-r6rs exceptions)
        (yuni scheme tests racket-r6rs conditions)
        (yuni scheme tests racket-r6rs io ports)
        (yuni scheme tests racket-r6rs io simple)
        (yuni scheme tests racket-r6rs programs)
        (yuni scheme tests racket-r6rs arithmetic fixnums)
        (yuni scheme tests racket-r6rs arithmetic flonums)
        (yuni scheme tests racket-r6rs arithmetic bitwise)
        (yuni scheme tests racket-r6rs syntax-case)
        (yuni scheme tests racket-r6rs hashtables)
        (yuni scheme tests racket-r6rs enums)
        (yuni scheme tests racket-r6rs eval)
        (yuni scheme tests racket-r6rs mutable-pairs)
        (yuni scheme tests racket-r6rs mutable-strings)
        (yuni scheme tests racket-r6rs r5rs)
        (yuni scheme tests racket-r6rs contrib))

(run-base-tests)

(run-reader-tests)
(run-unicode-tests)
(run-bytevectors-tests)
(run-lists-tests)
(run-sorting-tests)
(run-control-tests)
(run-records-syntactic-tests)
(run-records-procedural-tests)
(run-exceptions-tests)
(run-conditions-tests)
(run-io-ports-tests)
(run-io-simple-tests)
(run-programs-tests)
(run-arithmetic-fixnums-tests)
(run-arithmetic-flonums-tests)
(run-arithmetic-bitwise-tests)
(run-syntax-case-tests)
(run-hashtables-tests)
(run-enums-tests)
(run-eval-tests)
(run-mutable-pairs-tests)
(run-mutable-strings-tests)
(run-r5rs-tests)
(run-contrib-tests)

(report-test-results)

